feat: :sparkles: Miti Plasmo Extension : V2 ( Initial Version )
PoskOfficial/Nepali-calendar-web pull request #102
Opened 2024-10-26 15:56 UTC by pranishpaudel

2024-10-30 04:55 UTC, Parajulibkrm commented
@nirajacharyaa could you check this?

2024-10-30 07:55 UTC, nirajacharyaa commented
> @nirajacharyaa could you check this?

okay

2024-10-30 14:44 UTC, nirajacharyaa requested changes

2024-10-30 14:44 UTC, nirajacharyaa commented on apps/plasmo/src/components/Calendar/CalendarBody.tsx
> +        const data: CalendarDayData[] = await response.json()
you are fetching calendar data manually, you should fetch data of the current month and give user privilege to switch months with some UI

you need to use nepali-datetime npm package

2024-10-30 14:44 UTC, nirajacharyaa commented on apps/plasmo/src/components/Calendar/helpers/dateUtils.ts
> +}
this thing can be replaced by the date-fns package

2024-10-30 14:44 UTC, nirajacharyaa commented on apps/plasmo/src/components/Calendar/types/types.ts
> +}
the repo has internal type package, the types can be used from there

2024-10-30 14:44 UTC, nirajacharyaa commented on apps/plasmo/src/components/Calendar/helpers/dateUtils.ts
> +}
these tooo

2024-11-05 03:10 UTC, nirajacharyaa commented on apps/plasmo/src/components/Calendar/helpers/dateUtils.ts
> +
@pranishpaudel  please use `nepali-datetime` npm package, the English month change date is not even valid for each year, it varies.

2024-11-05 04:39 UTC, pranishpaudel commented
Sure

On Tue, Nov 5, 2024, 08:55 nirajacharyaa ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In apps/plasmo/src/components/Calendar/helpers/dateUtils.ts
> <https://github.com/PoskOfficial/Miti/pull/102#discussion_r1828668113>:
>
> > +// Mapping of Nepali months to approximate Gregorian (English) dates
> +const nepaliToEnglishMonthMap: {
> +  [key: string]: { month: number; startDay: number; year: number }
> +} = {
> +  "01": { month: 3, startDay: 14, year: 0 }, // Baisakh starts ~ April 14
> +  "02": { month: 4, startDay: 14, year: 0 }, // Jestha starts ~ May 14
> +  "03": { month: 5, startDay: 15, year: 0 }, // Ashadh starts ~ June 15
> +  "04": { month: 6, startDay: 16, year: 0 }, // Shrawan starts ~ July 16
> +  "05": { month: 7, startDay: 17, year: 0 }, // Bhadra starts ~ August 17
> +  "06": { month: 8, startDay: 17, year: 0 }, // Ashwin starts ~ September 17
> +  "07": { month: 9, startDay: 17, year: 0 }, // Kartik starts ~ October 17
> +  "08": { month: 10, startDay: 16, year: 0 }, // Mangsir starts ~ November 16
> +  "09": { month: 11, startDay: 16, year: 0 }, // Poush starts ~ December 16
> +  "10": { month: 0, startDay: 14, year: 1 }, // Magh starts ~ January 14
> +  "11": { month: 1, startDay: 13, year: 1 }, // Falgun starts ~ February 13
> +  "12": { month: 2, startDay: 14, year: 1 } // Chaitra starts ~ March 14
> +}
> +
> +// Convert Nepali year to English year
> +const getEnglishYear = (nepaliYear: number, nepaliMonth: string): number => {
> +  // Base conversion (approximate)
> +  const baseEnglishYear = nepaliYear - 57
> +
> +  // Adjust for months that span into the next year
> +  const monthData = nepaliToEnglishMonthMap[nepaliMonth]
> +  return baseEnglishYear + (monthData?.year || 0)
> +}
> +
>
> @pranishpaudel <https://github.com/pranishpaudel> please use
> nepali-datetime npm package, the English month change date is not even
> valid for each year, it varies.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PoskOfficial/Miti/pull/102#pullrequestreview-2414541898>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5H46GBBVOKS5JMG75ENPALZ7AZKTAVCNFSM6AAAAABQU5KWN2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMJUGU2DCOBZHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-07 08:49 UTC, pranishpaudel commented
Please check the latest commit and tell me if any updates are needed in it

2024-11-10 02:28 UTC, Parajulibkrm commented
Looks good for a starting point. Thanks @pranishpaudel

2024-11-10 02:28 UTC, merged